### ISSUE TITLE
Comments don't work as expected for nested selectors in SCSS

### ISSUE THREAD

**Issue by sergonius** [FullHuman/purgecss-docs#12]
### Expected outcome
```
.page .selector-1 { color: blue; }
.page .selector-2 { color: red; }
```

### Reality
```
.page {
  /* purgecss start ignore */
  .selector-1 { color: blue; }
  .selector-2 { color: red; }
  /* purgecss end ignore */
}
```
leaves me with:
```
.page {
  /* purgecss start ignore */
  /* purgecss end ignore */
}
```
while
```
/* purgecss start ignore */
.page {
  .selector-1 { color: blue; }
  .selector-2 { color: red; }
}
/* purgecss end ignore */
```
works as expected.

I guess this is a bug? If not, lets turn this baby into a feature!

**Comment by jsnanigans** [comment]
purgecss does not support any pre-processors like sass,scss,less,stylus you have to first compile your scss to css and then use purgecss

**Comment by sergonius** [comment]
That's a shame.
It still kinda works if you write the styles the way I have written above, though.
Lets say I have the following loaders for styles:

- style-loader
- css-loder
- postcss-loader
- sass-loader

The `purgecss-postcss` plugin fits here perfectly aside from what I described in this issue.
With Webpack 4, you would also be using `mini-css-extract-plugin`, so the need for `extract-text-webpack-plugin` and using all of these loaders and plugins together doesn't seem entirely obvious to me.

So personally, I will keep using it this way, whether it is supported or not – it still works!

**Comment by jsnanigans** [comment]
Its out of the scope of what this plugin is trying to accomplish.
Im not quite sure what you mean but purgecss-webpack-plugin works great with mini-css-extract-plugin. Its planned to make a purgecss-webpack-loader some day that you could just chain into the loaders but it will take quite some time to develop that.

Please feel free to use this plugin however you like but I can imagine quite a few problems when using it directly on sass

**Comment by sergonius** [comment]
```
use: [
	MiniCssExtractPlugin.loader,
	{ loader: 'css-loader' },
	{
		loader: 'postcss-loader',
		options: {
		  ident: 'postcss',
		  plugins: (loader) => [
		    require('autoprefixer')(autoprefixerSettings),
		    require('@fullhuman/postcss-purgecss')(purgeSettings),
		    require('cssnano')(nanoSettings),
		  ],
		},
	},
	{ loader: 'sass-loader' },
],
```

These are the settings I use for my `.scss` files and it works perfectly apart from the current little issue.

I mentioned `extract-text-webpack-plugin` because its in the PugeCSS docs and [this](https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage), where it says:
> :warning: Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.

This is out of the scope of this issue, but maybe it would just make sense to update the docs to the recommendations to avoid potential problems?

I will try the plugin out with `mini-css-extract-plugin` and see how that goes as well.

Thanks for the insights!

**Comment by jsnanigans** [comment]
there is an example for mini-css-extractor in the readme here
https://github.com/FullHuman/purgecss-webpack-plugin#with-mini-css-extract-plugin
